type: s
empty: false

shadowsocks:
  address: 127.0.0.1:6001

manager:
  address: 127.0.0.1:6002
  password: '123456'

plugins:
  telegram:
    use: false
    token: ''
  cli:
    use: false
  flowSaver:
    use: false
  email:
    use: false
    username: 'username'
    password: 'password'
    host: 'smtp.your-email.com'
  freeAccount:
    use: true
    startPort: 55000
    endPort: 65000
    flow: 10
    time: 60

db: 'db.sqlite'
